In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import os

import matplotlib.pyplot as plt

In [3]:
bb_data = pd.read_csv('data/bb_data_cleaned.csv')

In [4]:
bb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 654 entries, 0 to 653
Data columns (total 41 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           653 non-null    object
 1   Player Name    654 non-null    object
 2   School         650 non-null    object
 3   Pos            654 non-null    object
 4   Allstar/BT     654 non-null    object
 5   G              654 non-null    int64
 6   AB             654 non-null    int64
 7   R              654 non-null    int64
 8   H              654 non-null    int64
 9   2B             654 non-null    int64
 10  3B             654 non-null    int64
 11  HR             654 non-null    int64
 12  RBI            654 non-null    int64
 13  SB             654 non-null    int64
 14  CS             654 non-null    int64
 15  BB             654 non-null    int64
 16  SO             654 non-null    int64
 17  HBP            654 non-null    int64
 18  SH             654 non-null    int64
 19  SF             654 non-null    int64
 20  GDP            654 non-null    int64
 21  AVG            654 non-null    float64
 22  OBP            654 non-null    float64
 23  SLG            654 non-null    float64
 24  OPS            654 non-null    float64
 25  PA             654 non-null    int64
 26  TB             654 non-null    int64
 27  XBH            654 non-null    int64
 28  SECA           654 non-null    float64
 29  ISO            654 non-null    float64
 30  BABIP          654 non-null    float64
 31  BB%            654 non-null    object
 32  SO%            654 non-null    object
 33  SO/BB          654 non-null    object
 34  AB/HR          654 non-null    object
 35  HR%            654 non-null    object
 36  XBH%           654 non-null    object
 37  HiLvl          654 non-null    object
 38  MLB Years      654 non-null    object
 39  Stat Years     654 non-null    object
 40  Player Name.1  654 non-null    object
dtypes: float64(7), int64(19), object(15)
memory usage: 209.6+ KB

In [5]:
bb_data.head()

,Year,Player Name,School,Pos,Allstar/BT,G,AB,R,H,2B,...,BB%,SO%,SO/BB,AB/HR,HR%,XBH%,HiLvl,MLB Years,Stat Years,Player Name.1
0,2003-2006,Aaron Bates,NC State,1B,N,167,602,154,220,44,...,12.53,10.42,0.83,25.1,3.17,31.36,MLB,2009-2009,2003-2014,Aaron Bates
1,2002-2003,Aaron Hill,LSU,2B,N,124,487,114,168,45,...,11.55,7.07,0.61,27.1,3.1,41.07,MLB,2005-2017,2001-2017,Aaron Hill
2,2011-2013,Aaron Judge,Fresno State,OF,Y,169,594,130,205,41,...,15.06,19.11,1.27,33,2.51,32.2,MLB,2016-2020,2011-2020,Aaron Judge
3,2008-2010,Adam Eaton,Miami,CF-LF,N,158,621,169,211,45,...,7.85,11.57,1.47,25.9,3.19,41.23,MLB,2012-2020,2008-2020,Adam Eaton
4,2011-2013,Adam Engel,Louisville,OF,N,169,604,121,160,15,...,8.69,11.59,1.33,302,0.28,11.88,MLB,2017-2020,2011-2020,Adam Engel